### ISSUE TITLE
Some issues I noticed in the code...

### ISSUE THREAD

**Issue by SuperSajuuk** [JaredRNeal/announceBot#3]
Hi Dabbit

So I looked through the code, and noticed several errors:

1. Your permissions check for whether the user has the ability to use !announce is too late. Permissions checks must be the first thing in the command function, so as to avoid unnecessary code checks being made when the user is unable to actually utilise the command. Generally, a permissions check should return a boolean response of True or False.

2. In addition to the above, users with no permission should get no response from the bot, not a response telling them the command exists and that they have no perm. Silent responses mean that the user is not aware of the bot commands and won't be able to attempt to use them. 

3. In your commands, you print an error to console when an error occurs eg: https://github.com/JaredRNeal/announceBot/blob/39a71c8a7b5318bbd46848cef9c6428d41c874a7/commands/announce.py#L36 Printing an error to console is pointless because it will never be seen by anyone. If it's the wrong channel, it's better to either: do nothing, or respond saying "this is the wrong channel to run that command". In this case, doing nothing (ie silent response) is preferable.

4. When formatting strings, don't do this: https://github.com/JaredRNeal/announceBot/blob/39a71c8a7b5318bbd46848cef9c6428d41c874a7/commands/announce.py#L114
Instead, you should use more safer (and cleaner methods). In Python 3, you can use .format() with {} brackets for the substitution. I'm not sure about Python 2 formatting, but you should be able to do something like this:
```my_variable = "%s %s" % (previous_var1, previous_var2)```

Alongside that, this is wasted characters: https://github.com/JaredRNeal/announceBot/blob/39a71c8a7b5318bbd46848cef9c6428d41c874a7/commands/announce.py#L119

You can achieve the exact same result by doing: ```message_with_multiple_pings += "<@&" + Role_as_a_string + "> "```

Couldn't see anything else of concern, but I'll post them later if I see them.

**Comment by JaredRNeal** [comment]
Most of the issues listed here should be addressed with the latest update. It's still not perfect and there's more optimizations to do, but it's largely better.
